name: Build and publish package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment target. Can be "pypi" or "testpypi", or left as blank to skip publishing. Default is blank.'
        default: ""

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"

      - name: Build distributions
        run: pipx run build

      - name: Build, inspect, and display contents of distributions
        shell: bash
        run: |
          mkdir -p output/sdist
          tar -xf dist/*.tar.gz -C output/sdist

          echo -e '## View source distribution (SDist) contents\n' >> $GITHUB_STEP_SUMMARY
          echo -e '```\n' >> $GITHUB_STEP_SUMMARY
          (cd output/sdist && tree -a * | sed 's/^/    /' | tee -a $GITHUB_STEP_SUMMARY)
          echo -e '\n```\n' >> $GITHUB_STEP_SUMMARY

          mkdir -p output/wheel
          pipx run wheel unpack dist/*.whl -d output/wheel

          echo -e '## View binary distribution (wheel) contents\n' >> $GITHUB_STEP_SUMMARY
          echo -e '```\n' >> $GITHUB_STEP_SUMMARY
          (cd output/wheel && tree -a * | sed 's/^/    /' | tee -a $GITHUB_STEP_SUMMARY)
          echo -e '\n```\n' >> $GITHUB_STEP_SUMMARY

      - name: Upload sdist and wheel artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: distributions
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bpx
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    needs: [build]
    if: >-
      github.event_name == 'release' &&
      github.event.action == 'published' ||
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.target == 'pypi' ||
      github.event.inputs.target == 'testpypi'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        if: github.event.inputs.target == 'pypi' || github.event_name == 'release' && github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          packages-dir: dist

      - name: Upload to TestPyPI
        if: github.event.inputs.target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
